SRCDIR=$LLVM_STAGE2_SRC/compiler-rt
BUILDDIR=$LIBCXX_DIR/build
DESTDIR=$LIBCXX_DIR

rm -rf "$BUILDDIR"

CMAKE_ARGS=()
if [ "$CBUILD" != "$CHOST" ]; then
  case "$HOST_SYS" in
    linux) CMAKE_ARGS+=( -DCMAKE_HOST_SYSTEM_NAME=Linux ) ;;
    macos) CMAKE_ARGS+=( -DCMAKE_HOST_SYSTEM_NAME=Darwin ) ;;
  esac
  case "$TARGET_SYS" in
    linux) CMAKE_ARGS+=( -DCMAKE_SYSTEM_NAME=Linux ) ;;
    macos) CMAKE_ARGS+=( -DCMAKE_SYSTEM_NAME=Darwin ) ;;
  esac
fi

cmake -G Ninja -S "$LLVM_STAGE2_SRC/runtimes" -B "$BUILDDIR" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="$DESTDIR" \
  \
  -DCMAKE_ASM_COMPILER="$CC" \
  -DCMAKE_C_COMPILER="$CC" \
  -DCMAKE_CXX_COMPILER="$CXX" \
  -DCMAKE_AR="$AR" \
  -DCMAKE_RANLIB="$RANLIB" \
  -DCMAKE_LINKER="$LD" \
  \
  -DCMAKE_ASM_FLAGS="$CFLAGS" \
  -DCMAKE_C_FLAGS="$CFLAGS" \
  -DCMAKE_CXX_FLAGS="$CFLAGS" \
  -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS -L$LLVM_STAGE1_DIR/lib" \
  \
  -DCMAKE_SYSROOT="$SYSROOT" \
  \
  -DLLVM_ENABLE_LLD=ON \
  -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" \
  -DLLVM_DEFAULT_TARGET_TRIPLE="$TARGET_TRIPLE" \
  \
  -DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON \
  -DLIBCXX_HAS_MUSL_LIBC=ON \
  -DLIBCXX_USE_COMPILER_RT=ON \
  -DLIBCXX_ENABLE_STATIC=ON \
  -DLIBCXX_ENABLE_SHARED=OFF \
  -DLIBCXX_ABI_VERSION=2 \
  -DLIBCXX_CXX_ABI=libcxxabi \
  -DLIBCXX_ENABLE_NEW_DELETE_DEFINITIONS=ON \
  -DLIBCXX_ENABLE_EXPERIMENTAL_LIBRARY=OFF \
  -DLIBCXX_INCLUDE_TESTS=OFF \
  -DLIBCXX_INCLUDE_BENCHMARKS=OFF \
  -DLIBCXX_LINK_TESTS_WITH_SHARED_LIBCXX=OFF \
  \
  -DLIBCXXABI_ENABLE_SHARED=OFF \
  -DLIBCXXABI_USE_LLVM_UNWINDER=ON \
  -DLIBCXXABI_ENABLE_STATIC_UNWINDER=ON \
  -DLIBCXXABI_USE_COMPILER_RT=ON \
  -DLIBCXXABI_ENABLE_NEW_DELETE_DEFINITIONS=OFF \
  -DLIBCXXABI_INCLUDE_TESTS=OFF \
  -DLIBCXXABI_LINK_TESTS_WITH_SHARED_LIBCXXABI=OFF \
  \
  -DLIBUNWIND_USE_COMPILER_RT=ON \
  -DLIBUNWIND_ENABLE_SHARED=OFF \
  \
  ${CMAKE_ARGS[@]}

ninja -C "$BUILDDIR" cxx cxxabi unwind
ninja -C "$BUILDDIR" install

rm -rf "$BUILDDIR"
mkdir "$DESTDIR/usr"
mv "$DESTDIR/include" "$DESTDIR/usr/include"
